smartstash/core/urls.py
from django.conf.urls import patterns, url
from smartstash.core import views


urlpatterns = patterns(
    '',
    url(r'^$', views.view_items, name='view'),
    url(r'^list/$', views.save_list, name='list'),
)

smartstash/images/urls.py
from django.conf.urls import patterns, include, url
from smartstash.images import views

urlpatterns = patterns(
    '',
    url(r'^resize/(?P<size>[0-9]+)/$', views.resize, name='resize'),
)

smartstash/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from smartstash.core import views


urlpatterns = patterns(
    '',
    url(r'^$', views.site_index, name='site-index'),
    url(r'^discoveries/', include('smartstash.core.urls',
        namespace='discoveries')),
    url(r'^images/', include('smartstash.images.urls',
        namespace='image')),


    url(r'^auth/', include('smartstash.localauth.urls', namespace='auth')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'', include('social_auth.urls')),

    # static site content pages
    url(r'^connect/', TemplateView.as_view(template_name='connect.html'),
        name='connect'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'),
        name='about'),

    url(r'^favicon.ico$', RedirectView.as_view(url='/static/img/favicon.ico')),
    # redirect from old/original results page url to new url
    url(r'^stash/$', RedirectView.as_view(url='/discoveries/')),



    # examples
    # url(r'^input/', include('smartstash.input.urls',
    #     namespace='input')
    # url(r'^$', 'smartstash.views.home', name='home'),
    # url(r'^smartstash/', include('smartstash.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

smartstash/core/forms.py
import os
from django import forms
from django.conf import settings
from social_auth.models import UserSocialAuth
from pyzotero import zotero


class InputForm(forms.Form):

    text = forms.CharField(
        label='Cut and paste a block of text.',
        help_text='Cut and paste a block of text.',
        widget=forms.Textarea(attrs={'tabindex': 4, 'id': 'texto'}),
        initial=open(os.path.join(settings.STATICFILES_DIRS[0], "default.txt")).read(),
        required=True
        )

    # TODO: alternate inputs- zotero url?
    # use urlfield if appropriate
    # make text input not required, but add form validation
    # so at least one input is required for form to be valid

    def clean(self):
        cleaned_data = super(InputForm, self).clean()

        text = cleaned_data.get('text', '').strip()
        # zotero_user = cleaned_data.get('zotero_user', '').strip()

        if not text:
            raise forms.ValidationError('Please enter some text.')
        # if not any([text, zotero_user]):
        #     raise forms.ValidationError('Please enter some text or a Zotero username.')

        # Always return the full collection of cleaned data.
        return cleaned_data


class ZoteroInputForm(forms.Form):
    default_choices = [('recent', 'recent entries')]
    default_field_args = {
        'help_text': 'Choose which part of your Zotero library to use',
        'required': True
    }
    selection = forms.ChoiceField(choices=default_choices, **default_field_args)

    def __init__(self, user=None, *args, **kwargs):
        super(ZoteroInputForm, self).__init__(*args, **kwargs)

        if user is not None:
            # retrieve zotero user info
            zotero_user = UserSocialAuth.objects.get(user=user, provider='zotero')
            zot = zotero.Zotero(zotero_user.uid, 'user', zotero_user.tokens['oauth_token'])

            # generate a list of tuples: collection key, name
            collections = []
            for coll in zot.collections():
                collections.append(('collection:%s' % coll['collectionKey'],
                                     coll['name']))

            # similar for groups
            groups = []
            for grp in zot.groups():
                groups.append(('group:%s' % grp['group_id'], grp['name']))

            # similar for tags
            # NOTE: tag results for my library has tags with type 0 (tags I created)
            # and tags with type 1 - seems to be subjects from records (?);
            # only including type 1 for now
            tags = [('tag:%s' % t['tag'], t['tag']) for t in zot.tags()
                    if t['type'] == 0]

            # if we found any groups or collections, re-init choice field
            # with the new list
            if collections or groups or tags:
                choices = [] + self.default_choices
                if collections:
                    choices.append(('Collections', collections))
                if groups:
                    choices.append(('Groups', groups))
                if tags:
                    choices.append(('Tags', tags))
                self.fields['selection'] = forms.ChoiceField(
                    choices=choices,
                    widget=forms.widgets.Select(attrs={'size': 10})
                    )

smartstash/core/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.utils.html import escape
from social_auth.models import UserSocialAuth
import logging
from pyzotero import zotero
import time
import guess_language
import random

# from smartstash.core import zotero
from smartstash.core.forms import InputForm, ZoteroInputForm
from smartstash.core.utils import common_words, get_search_terms
from smartstash.core.api import DPLA, Europeana, Flickr, Trove

logger = logging.getLogger(__name__)

# see fixme in auth.views
escapes = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;",
    ">": "&gt;",
    "<": "&lt;",
    ",": "",
    ":": "",
    "-": ""
}


@require_http_methods(["GET", "POST"])   # TODO: support HEAD requests?
def site_index(request):
    # preliminary site index page

    # TODO, possibly -- might be worth supporting HEAD requests
    # since this is the site index

    if request.method == 'GET':
        # on get request, initialize an empty form for display
        form = InputForm()

        if request.user.is_authenticated():
            zotero_form = ZoteroInputForm(user=request.user)
        else:
            zotero_form = None

    elif request.method == 'POST':
        # on post, init form based on posted data
        # if form is invalid, redisplay input form with error messages

        submit_type = request.POST.get('submit')

        if submit_type == 'text_input':
            form = InputForm(request.POST)
        elif submit_type == 'zotero_input':
            form = ZoteroInputForm(data=request.POST, user=request.user)

        if form.is_valid():

            # TODO: break out into sub function (?)
            if submit_type == 'text_input':

                # actual logic here - infer search terms, query apis, display stuff

                text = form.cleaned_data['text']
                search_terms = {}

                lang = guess_language.guessLanguage(text)
                logger.debug('language detected as %s' % lang)
                common_terms = common_words(text, 15, lang)
                dbpedia_terms = get_search_terms(text, lang)

                # too many terms? phrase? didn't get results when combining
                # TODO: combine dbpedia + common terms; randomize from dbpedia results
                #search_terms['keywords'].extend(dbpedia_terms['keywords'])

                search_terms['keywords'] = list(dbpedia_terms['keywords'])[:10]

                # if no terms found in dbpedia, use common terms instead
                # (todo: should be some kind of combination)
                if not search_terms['keywords']:
                    search_terms['keywords'] = common_terms['keywords']

                # within dbpedia_terms there are now lists for
                # people
                # places
                # dates {'early': ,'late': }
                # people and places were reconciled against DBpedia. Dates contains
                # only four digit values and could be passed to

            # TODO: probably should also be separate function
            elif submit_type == 'zotero_input':
                selection = form.cleaned_data['selection']

                # retrieve zotero user info to get zotero access
                zotero_user = UserSocialAuth.objects.get(user=request.user, provider='zotero')
                zot = zotero.Zotero(zotero_user.uid, 'user', zotero_user.tokens['oauth_token'])
                if selection == 'recent':
                    items = zot.items(limit=100)
                else:
                    seltype, val = selection.split(':')
                    if seltype == 'collection':
                        items = zot.collection_items(val)
                    elif seltype == 'group':
                        zotgrp = zotero.Zotero(val, 'group', zotero_user.tokens['oauth_token'])
                        items = zotgrp.items(limit=100)
                    elif seltype == 'tag':
                       items = zot.tag_items(val)

                textdata = []
                # TODO: logic for generating text/search terms from zotero items should be
                # in a separate method or class
                for item in items:
                    if item['itemType'] == 'note':
                        textdata.append(item['note'])  # might be html ?
                    else:
                        data = []
                        for field in ['title', 'abstractNote']:
                            if field in item:
                                data.append(item[field])
                        for creator in item.get('creators', []):
                            if 'name' in creator:
                                data.append(creator['name'])
                            elif 'firstName' in creator and 'lastName' in creator:
                                data.append('%(firstName)s %(lastName)s' % creator)
                        textdata.append(' '.join(data))


                text = ' '.join(textdata)
                search_terms = common_words(text)

                # sanitize
                for key, val in search_terms.iteritems():
                    # val is a list of terms
                    search_terms[key] = [escape(v) for v in val]

        # if form is valid,
        # for either text input or zotero where we got terms

        # store search terms in the session so we can redirect
        request.session['search_terms'] = search_terms

        # redirect
        # NOTE: should probably be http code 303, see other
        return HttpResponseRedirect(reverse('discoveries:view'))

        # if not valid: pass through and redisplay errors

    return render(request, 'core/site_index.html',
                  {'input_form': form, 'zotero_form': zotero_form})



# TODO: view copied from display.views, code probably needs to be refactored
# into a single app
def sanitizeString(s):
    result = ""
    for c in s: result += escapes.get(c, c)
    return result


def view_items(request):
    search_terms = request.session.get('search_terms', None)

    error_messages = {
        'no_terms': '''Whoops! Somehow we didn't come up with any search
            terms for you. Put some different text in the box and we'll
            give it another go.''',
        'no_results': '''Our sources couldn't find anything for the
            search terms created from your text. Put some different text
            in the box and we'll give it another go.'''
    }


    # if no search terms, return to site index
    if search_terms is None or not search_terms['keywords']:

        if search_terms is not None and 'keywords' in search_terms:
            messages.error(request, error_messages['no_terms'])

        # TODO: add a django session message here,
        # especially if they posted data and we didn't get any keywords
        return HttpResponseRedirect(reverse('site-index'))

    # # clear the session
    # # TODO: should probably be more specific what we need to clear (zotero auth info?)
    # # since other items may be added to the session at some point (e.g. messages)
    # for key, value in request.session.items():
    #     if key != 'search_terms':
    #         del request.session[key]

    # sanitize the search terms for API queries

    # encode the search terms for safety
    search_terms['keywords'] = [sanitizeString(s) for s in search_terms['keywords']]

    start = time.time()
    error = False
    try:
        dpla_items = DPLA.find_items(**search_terms)
    except Exception as err:
        logger.error('Error querying DPLA - %s' % err)
        error = True
        dpla_items = []

    try:
        euro_items = Europeana.find_items(**search_terms)
    except Exception as err:
        logger.error('Error querying Europeana - %s' % err)
        error = True
        euro_items = []

    try:
        flkr_items = Flickr.find_items(**search_terms)
    except Exception as err:
        logger.error('Error querying Flickr - %s' % err)
        error = True
        flkr_items = []

    try:
        trove_items = Trove.find_items(**search_terms)
    except Exception as err:
        logger.error('Error querying Trove - %s' % err)
        error = True
        trove_items = []

    logger.info('Queried 4 sources in %.2f sec' % (time.time() - start))

    # TODO: should we remove from source list if we failed?
    sources = [DPLA, Europeana, Flickr, Trove]

    # combine all results into a single list and then shuffle them together
    logger.info('Number of items by source: DPLA=%d, Europeana=%d, Flickr=%d, Trove=%d' % \
                 (len(dpla_items), len(euro_items), len(flkr_items), len(trove_items)))
    items = dpla_items + euro_items + flkr_items + trove_items
    request.session['items'] = items

    # if none of the API calls worked, message & return to home page
    if not items:
        # if error is true, at least one of the api calls failed
        # otherwise, presumably we callled all apis and didn't get any results (?)
        messages.error(request, error_messages['no_terms'])
        return HttpResponseRedirect(reverse('site-index'))

    # shuffle images so we get a more even mix, esp. if one source
    # (such as flickr) returns more items than the others
    random.shuffle(items)

    # NOTE: we may need to clear the cache when we do a 'start over'....

    return render(request, 'core/view.html',
                  {'items': items, 'query_terms': search_terms, 'sources': sources})


def save_list(request):
    items = request.session.get('items', None)
    # no items to save; error & redirect to index
    if items is None:
        messages.error(request, '''Whoops! Somehow we didn't find any discoveries to save.''')
        return HttpResponseRedirect(reverse('site-index'))

smartstash/core/templates/core/save_list.html
{% extends 'page_base.html' %}
{% load static %}

{% block title %}Save Your MagicStash Items{% endblock %}

{% block content %}

<h3>Instructions: This list is generated from your last result set. To save it,
copy and paste it into a text editor or select Save from the File menu in your
browser.</h3>
<p><strong>Terms Used:</strong> {{ query_terms.keywords|join:', ' }}<br />
<strong>Sources Used:</strong>
{% for source in sources %}<a href="{{ source.url }}" target="_blank">{{ source.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
</p>

<div>
<ol>
{% for item in items %}
    <li>{{ item.title }}: {{ item.url }}. <span class="aggregator">From {{ item.aggregator }}.</span></li>
{% endfor %}
</ol>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-1.10.2.js' %}">\x3C/script>')</script>
<!--  <script src="http://isotope.metafizzy.co/jquery.isotope.min.js"></script> -->
<script src="{% static 'js/scripts_view.js' %}"></script>
{% endblock %}

smartstash/core/templates/core/saveme.html
{% extends 'page_base.html' %}
{% load static %}

{% block title %}Save Your MagicStash Items{% endblock %}

{% block content %}

<h3>Instructions: This list is generated from your last result set. To save it,
copy and paste it into a text editor or select Save from the File menu in your
browser.</h3>
<p><strong>Terms Used:</strong> {{ query_terms.keywords|join:', ' }}<br />
<strong>Sources Used:</strong>
{% for source in sources %}<a href="{{ source.url }}" target="_blank">{{ source.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
</p>

<div>
<ol>
{% for item in items %}
    <li>{{ item.title }}: {{ item.url }}. <span class="aggregator">From {{ item.aggregator }}.</span></li>
{% endfor %}
</ol>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-1.10.2.js' %}">\x3C/script>')</script>
<!--  <script src="http://isotope.metafizzy.co/jquery.isotope.min.js"></script> -->
<script src="{% static 'js/scripts_view.js' %}"></script>
{% endblock %}

smartstash/core/templates/core/site_index.html
{% extends 'index_base.html' %}
{% load static %}

{% block content %}
<!--<hr/>-->
	<div class="nine columns">

<div id="hippo" style="display: none;">
  <img src="{% static 'img/feedthemachine.gif' %}" alt="Image of Hippo: Feeding the Machine" />
</div>
		<h3 class="start">Let’s Get Started.</h3>

		<h3>Grab some text.</h3>
		<h5>Got a paper you’ve written? How about some research notes? Favorite
        song lyrics? Throw it into the Serendip-o-matic! Not sure what to use?
        Try <a href="http://en.wikipedia.org/wiki/Wikipedia:Today's_featured_article"
        target="_blank">Wikipedia's daily featured article</a> or try it out with the sample text below.</h5>

    {# display modal messages in the same space as form validation error #}
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><img src="{% static 'img/warning.png' %}" valign="top" height="8%" width="8%" alt="Error" />{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

	<div class="error">{{ input_form.non_field_errors }}</div>
	
	<form name="hippo" method="post" action="{% url 'site-index' %}">{% csrf_token %}

      {{ input_form.text }}
	  
  <input type="submit" id="magic-button" class="magic" value="Make some magic!"/>
</div>
<div class="pipe one columns"></div>

<div class="five columns" >


	
	<div class="zot">
		<h3>
            <img class="zotero" src="{% static 'img/zotero.png' %}" alt="Zotero" style="margin:0;padding:0;" />, anyone?
        </h3>
    <!-- Needs label from Django -->
	<h5>Or got a Zotero account?<br />
    Enter your username to give your reference library a whirl!</h5>
   {{ input_form.zotero_user }}
    <input type="submit" id="magic-button" class="magic" value="Go!"/>
    <h5>Need <a href="https://docs.google.com/document/d/1okQAQfqTdDeCA8FNIDv5GGQcu0y7c8r5s4FdxjJ1J2s/edit?usp=sharing" target="_blank">help or more info about Zotero integration</a>?</h5>
	 </div>
<!--	<div style="width: 300px; margin-left:25px;">
		<div>
			<script src="https://platform.twitter.com/widgets.js"></script> --> <!-- Twitter Widget Library -->
<!--			<a href="https://twitter.com/intent/follow?&screen_name=serendipomatic" target="_blank">
				<img src="{% static 'img/social-media-icons/57x57/twitter.png' %}" alt="Follow the Serendhippo on Twitter" style="height:25px;width:25px;float:left;" />
			</a>
			<span style="padding:0;margin:0 0 0 4px;float:left;">
				<a href="https://twitter.com/intent/follow?&screen_name=serendipomatic" target="_blank">Follow the Serendhippo on Twitter</a>
			</span>
		</div>
		<div style="height:10px;clear:both;"></div>
		<div>
			<a href="http://www.cafepress.com/serendipomatic" target="_blank">
				<img src="{% static 'img/cplogo.png' %}" alt="Get Serendip-o-matic on CafePress.com" style="height:25px;width:25px;float:left;" />
			</a>
			<span style="padding:0;margin:0 0 0 4px;float:left;">
				<a href="http://www.cafepress.com/serendipomatic" target="_blank">Get Some Serendip-o-matic Swag</a>
			</span>
		</div>
	</div>
-->
</div>

</form>

<script>
//function eraseText() {
//  window.jQuery.get('static/default.txt', function(data){
//    if (document.getElementById("texto").value == data){
//      document.getElementById("texto").value = "";
//    }
//  })
//}

function loading() {
    $("#loader").show();
    $("#loader").animate({
        top: -200}, 1500);
}
</script>

 <script>
$( "#hippo" ).dialog({
      autoOpen: false,
      height: 190,  // Image is 157h x 209w
      width: 240, //209
      modal: false
});

$( ".magic" ).click(function() {
	$( "#hippo" ).dialog( "open" );
});
</script>

<script>
$(document).ready(function(){
$('#texto')
    .each(function() {
        $(this).data('default', this.value);
    })
    .focusin(function() {
        if ( this.value == $(this).data('default') ) {
            this.value = '';    
        }
    });
});
</script>   

	</div><!-- container -->

<!-- End Document
================================================== -->

{% endblock %}

smartstash/core/templates/core/view.html
{% extends 'page_base.html' %}
{% load static %}

{% block title %}MagicStash Items Display{% endblock %}

{% block extra-head %}
<!-- add extra css/js here -->
<style>
  .ui-tooltip {
    font-size: smaller;
  }
</style>
{% endblock %}

{% block content %}
<hr />
<div class="queryhead">

<div class="ten columns">

    <div class="querytitle">Serendip-o-matic ran with these words from your text:</div>
    <div class="querystyle"> {{ query_terms.keywords|join:', ' }}</div>


  <p><strong>Sources used:</strong>
  {% for source in sources %}<a href="{{ source.url }}" target="_blank">{{ source.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
</div>


<div class="querysearch four columns">
<!--
<p class="results-menu"><a class="results-menu" href="{% url 'site-index' %}">Try Again</a></p>
<p class="results-menu"><a class="results-menu" href="{% url 'discoveries:list' %}" target="_blank">Save as Text</a> <img class="results-menu" src="{% static 'img/question_mark.png' %}" alt="Help" title="Generates a text list of result links which you can print, copy to an editor, or save in your browser. Opens in a new window." /></p>
<p class="results-menu">
	<a class="results-menu" href="javascript:var d=document,s=d.createElement('script');s.src='https://www.zotero.org/bookmarklet/loader.js';(d.body?d.body:d.documentElement).appendChild(s);void(0);">Save to Zotero</a>
	<img class="results-menu" src="{% static 'img/question_mark.png' %}" alt="Help" title="Saves to your Zotero library with Zotero Standalone. If you do not have Zotero Standalone open, you may also save results to your Zotero library by clicking the Folder icon with the tooltip 'Save to Zotero COinS' in your browser's address bar." />
</p>
-->
<div class="gohome">
<a href="{% url 'site-index' %}">Go home and feed the machine new text!</a>
</div>
<p>Like what you see? <a href="{% url 'discoveries:list' %}" target="_blank" class="altsave" title="If you have the Zotero plugin running in your browser, you can also save to your Zotero library. Just click the folder icon in your browser's address bar (it should say 'Save to Zotero (COinS)' if you mouse over it).">Save these results</a> (will open on another page)
</p>

{# <a href="{% url 'site-index' %}"><button class="magic" tabindex="5">Refresh Results</button></a> #}
{# <a href="{% url 'saveme' %}" target="_blank"><button class="magic" tabindex="6">Rearrange Results</button></a> #}
</div>
</div>
<div class="clearfix"></div>

<div id="container"> {# force result image div to full width #}
{% for item in items %}



<!-- Insert below into results page. Semi-opaque overlay from top of differently sized images. Suck text data into .overlay and image into .imageframe -->

<div class="imageframe">
  {% if 'flickr.com' in item.thumbnail %}
        <img src="{{ item.thumbnail }}" alt=" " >
  {% else %}
        <img src="{% url 'image:resize' size=300 %}?url={{ item.thumbnail }}" alt="{{ item.title }}" >
  {% endif %}
	<div class="overlay">
		<div class="iso_title"><a href="{{ item.url }}" target="_blank">"{{ item.title|truncatechars:80 }}"</a></div>
    {% comment %} {# not displaying date for the moment #}
    {% if item.date %}
		<div class="iso_date">{{ item.date }}</div>
    {% endif %}
    {% endcomment %}
    {% if item.source %}
    <div class="iso_source">from {{ item.source }}
      {% if item.aggregator == 'Flickr Commons' or item.aggregator == 'Europeana' %} on {{ item.aggregator }}{% endif %}
    </div>
    {% endif %}
	</div>
  {# span with citation information as COinS for zotero harvest #}
  <span class="Z3988" title="{{ item.coins_citation }}"></span>


</div>

<!-- Change the number in the add filter depending on the number of tabindexes required before results. -->
<!--
<div class="hover panel" tabindex="{{ forloop.counter|add:6 }}">
	<div class="front">
		<div class="pad">
		<div class="photo">
	<div class="iso_image"><a href="{{ item.url }}" target="_blank">
            <img class="imgLiquidFill" src="{{ item.thumbnail }}" alt="{{ item.title }}" style="width:150px; height:150px;">
        </a></div>
		</div>
		</div>
	</div>
	<div class="back">
		<div class="pad">
			<div class="iso_date">Date: {{ item.date }}</div>
			<div class="iso_title">Title: <a href="{{ item.url }}">{{ item.title }}</a></div>
			<div class="iso_title">Location: <a href="{{ item.location }}">{{ item.location }}</a></div>
		</div>
	</div>
</div>
<input type="hidden" value="{{ item.location }}"/>
</div>

-->
{% endfor %}
</div>

<p style="text-align: center; margin: 15px 0 5px 0;">
  <a href="#top"><button tabindex="1000">Return to Top</button></a></p>
  {# FIXME: button is not actually valid inside a; adjust so styles we can use a class="button" #}


{% comment %}
{{ item.title|default:'(no source)' }}
{% endcomment %}

<!-- Jquery and JQuery UI -->
<!--
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-1.10.2.js' %}">\x3C/script>')</script>

<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
-->


<!--  <script src="http://isotope.metafizzy.co/jquery.isotope.min.js"></script> -->
<script src="{% static 'js/isotope-1.5.25.js' %}"></script>
<script src="{% static 'js/scripts_view.js' %}"></script>
<script src="{% static 'js/fake-element.js' %}"></script>
<script type="text/javascript">
   // Populates broken image links with default image
   $(window).load(function() {
      $("img").each(function(){
         var image = $(this);
         if(image.context.naturalWidth == 0 ||
         image.readyState == 'uninitialized'){
            $(image).unbind("error").attr(
                "src", "{% static 'img/fillerhippo.png' %}"
            );
                        $(image).unbind("error").attr(
                "height", "249"
            );
                        $(image).unbind("error").attr(
                "width", "248"
            );
         }
    });
});
</script>
 <script>
    $(function(){

      var $container = $('#container');

      $container.imagesLoaded( function(){
        $container.isotope({
          itemSelector : '.imageframe'
        });
      });


    });
  </script>

  <script>

// For sorting
$(document).ready(function() {
    $('#sort-by a').click(function(){
      // get href attribute, minus the '#'
      var sortName = $(this).attr('href').slice(1);
      $('#container').isotope({ sortBy : sortName });
      return false;
    });
});
</script>

<script>
	$(".altsave").tooltip({
		position: {
			my: "center bottom-20",
			at: "center top"
		}
	}
	);
</script>
{% endblock %}